version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - /path/to/your/rabbitmq:/var/lib/rabbitmq
  application-consumer:
    build: ./MailService
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - application-producer
      - rabbitmq
  application-producer:
    build: ./SynopApp
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - rabbitmq
